/**
 * ADMIN - PDF TEMPLATE MANAGEMENT
 * Manage PDF generation templates for daily and weekly plans
 */

import React, { useState } from 'react';
import { View, Text, ScrollView, Pressable, TextInput, Switch } from 'react-native';
import {
  FileText,
  Plus,
  Edit,
  Trash2,
  Eye,
  Download,
  Settings,
  Check,
  Layout,
  Type,
  Palette,
  Image,
  Grid,
  AlignLeft,
  Calendar,
  Dumbbell,
  Utensils,
  Timer,
  Copy,
  Star,
  AlertCircle,
} from 'lucide-react-native';
import { cn } from '@/lib/cn';

// ==================== TYPES ====================

type PDFTemplateType = 'daily' | 'weekly';
type PDFTemplateStatus = 'active' | 'draft' | 'archived';

interface PDFTemplate {
  id: string;
  name: string;
  type: PDFTemplateType;
  description: string;
  status: PDFTemplateStatus;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  settings: PDFTemplateSettings;
  usageCount: number;
}

interface PDFTemplateSettings {
  layout: {
    orientation: 'portrait' | 'landscape';
    margins: { top: number; right: number; bottom: number; left: number };
    fontSize: 'small' | 'medium' | 'large';
  };
  branding: {
    showLogo: boolean;
    logoPosition: 'top-left' | 'top-center' | 'top-right';
    primaryColor: string;
    accentColor: string;
    showFooter: boolean;
    footerText: string;
  };
  sections: {
    includeWorkout: boolean;
    includeMeals: boolean;
    includeFasting: boolean;
    includeNutrition: boolean;
    includeProgress: boolean;
    includeNotes: boolean;
    sectionOrder: string[];
  };
  style: {
    headerStyle: 'minimal' | 'standard' | 'bold';
    tableStyle: 'simple' | 'bordered' | 'striped';
    showIcons: boolean;
    showImages: boolean;
  };
}

// ==================== MOCK DATA ====================

const DEFAULT_SETTINGS: PDFTemplateSettings = {
  layout: {
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    fontSize: 'medium',
  },
  branding: {
    showLogo: true,
    logoPosition: 'top-left',
    primaryColor: '#10b981',
    accentColor: '#a78bfa',
    showFooter: true,
    footerText: 'Generated by FitLife App',
  },
  sections: {
    includeWorkout: true,
    includeMeals: true,
    includeFasting: true,
    includeNutrition: true,
    includeProgress: false,
    includeNotes: true,
    sectionOrder: ['fasting', 'workout', 'meals', 'nutrition', 'notes'],
  },
  style: {
    headerStyle: 'standard',
    tableStyle: 'striped',
    showIcons: true,
    showImages: false,
  },
};

const MOCK_TEMPLATES: PDFTemplate[] = [
  {
    id: 't1',
    name: 'Daily Plan - Standard',
    type: 'daily',
    description: 'Default daily plan template with all sections included',
    status: 'active',
    isDefault: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-28T10:30:00Z',
    createdBy: 'admin@fitlife.com',
    settings: DEFAULT_SETTINGS,
    usageCount: 245,
  },
  {
    id: 't2',
    name: 'Daily Plan - Compact',
    type: 'daily',
    description: 'Condensed daily plan for quick reference',
    status: 'active',
    isDefault: false,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-25T14:00:00Z',
    createdBy: 'admin@fitlife.com',
    settings: {
      ...DEFAULT_SETTINGS,
      layout: { ...DEFAULT_SETTINGS.layout, fontSize: 'small' },
      sections: { ...DEFAULT_SETTINGS.sections, includeNotes: false, includeProgress: false },
      style: { ...DEFAULT_SETTINGS.style, headerStyle: 'minimal', showImages: false },
    },
    usageCount: 89,
  },
  {
    id: 't3',
    name: 'Weekly Overview',
    type: 'weekly',
    description: 'Complete weekly plan with all days at a glance',
    status: 'active',
    isDefault: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-27T09:15:00Z',
    createdBy: 'admin@fitlife.com',
    settings: {
      ...DEFAULT_SETTINGS,
      layout: { ...DEFAULT_SETTINGS.layout, orientation: 'landscape' },
    },
    usageCount: 156,
  },
  {
    id: 't4',
    name: 'Workout Only',
    type: 'daily',
    description: 'Exercise-focused template without meal information',
    status: 'draft',
    isDefault: false,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
    createdBy: 'editor@fitlife.com',
    settings: {
      ...DEFAULT_SETTINGS,
      sections: {
        ...DEFAULT_SETTINGS.sections,
        includeMeals: false,
        includeNutrition: false,
        includeFasting: false,
      },
    },
    usageCount: 0,
  },
  {
    id: 't5',
    name: 'Nutrition Focus',
    type: 'daily',
    description: 'Detailed nutrition and meal planning template',
    status: 'archived',
    isDefault: false,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-22T11:00:00Z',
    createdBy: 'admin@fitlife.com',
    settings: {
      ...DEFAULT_SETTINGS,
      sections: {
        ...DEFAULT_SETTINGS.sections,
        includeWorkout: false,
      },
    },
    usageCount: 34,
  },
];

// ==================== COMPONENTS ====================

// Status badge
function StatusBadge({ status }: { status: PDFTemplateStatus }) {
  const config = {
    active: { bg: 'bg-emerald-500/20', text: 'text-emerald-400', label: 'Active' },
    draft: { bg: 'bg-amber-500/20', text: 'text-amber-400', label: 'Draft' },
    archived: { bg: 'bg-slate-500/20', text: 'text-slate-400', label: 'Archived' },
  };

  const { bg, text, label } = config[status];

  return (
    <View className={cn('rounded-full px-2.5 py-1', bg)}>
      <Text className={cn('text-xs font-medium', text)}>{label}</Text>
    </View>
  );
}

// Type badge
function TypeBadge({ type }: { type: PDFTemplateType }) {
  const config = {
    daily: { bg: 'bg-cyan-500/20', text: 'text-cyan-400', label: 'Daily' },
    weekly: { bg: 'bg-violet-500/20', text: 'text-violet-400', label: 'Weekly' },
  };

  const { bg, text, label } = config[type];

  return (
    <View className={cn('rounded px-2 py-0.5', bg)}>
      <Text className={cn('text-xs', text)}>{label}</Text>
    </View>
  );
}

// Template card
function TemplateCard({
  template,
  onEdit,
  onPreview,
  onDuplicate,
  onDelete,
  onSetDefault,
}: {
  template: PDFTemplate;
  onEdit: () => void;
  onPreview: () => void;
  onDuplicate: () => void;
  onDelete: () => void;
  onSetDefault: () => void;
}) {
  const { sections } = template.settings;
  const includedSections = [
    sections.includeWorkout && 'Workout',
    sections.includeMeals && 'Meals',
    sections.includeFasting && 'Fasting',
    sections.includeNutrition && 'Nutrition',
  ].filter(Boolean);

  return (
    <View className="rounded-2xl border border-slate-700 bg-slate-900 p-5">
      {/* Header */}
      <View className="mb-4 flex-row items-start justify-between">
        <View className="flex-1">
          <View className="flex-row items-center gap-2">
            <View className="h-10 w-10 items-center justify-center rounded-xl bg-slate-800">
              <FileText size={20} color="#a78bfa" />
            </View>
            <View className="flex-1">
              <View className="flex-row items-center gap-2">
                <Text className="text-lg font-semibold text-white">{template.name}</Text>
                {template.isDefault && (
                  <View className="flex-row items-center rounded-full bg-amber-500/20 px-2 py-0.5">
                    <Star size={10} color="#f59e0b" />
                    <Text className="ml-1 text-xs text-amber-400">Default</Text>
                  </View>
                )}
              </View>
              <View className="mt-1 flex-row items-center gap-2">
                <TypeBadge type={template.type} />
                <StatusBadge status={template.status} />
              </View>
            </View>
          </View>
        </View>

        {/* Actions dropdown */}
        <View className="flex-row gap-1">
          <Pressable onPress={onPreview} className="rounded-lg bg-slate-800 p-2">
            <Eye size={16} color="#94a3b8" />
          </Pressable>
          <Pressable onPress={onEdit} className="rounded-lg bg-slate-800 p-2">
            <Edit size={16} color="#94a3b8" />
          </Pressable>
          <Pressable onPress={onDuplicate} className="rounded-lg bg-slate-800 p-2">
            <Copy size={16} color="#94a3b8" />
          </Pressable>
          {!template.isDefault && (
            <Pressable onPress={onDelete} className="rounded-lg bg-slate-800 p-2">
              <Trash2 size={16} color="#64748b" />
            </Pressable>
          )}
        </View>
      </View>

      {/* Description */}
      <Text className="mb-4 text-sm text-slate-400">{template.description}</Text>

      {/* Included sections */}
      <View className="mb-4">
        <Text className="mb-2 text-xs font-medium uppercase text-slate-500">Included Sections</Text>
        <View className="flex-row flex-wrap gap-2">
          {sections.includeWorkout && (
            <View className="flex-row items-center rounded-lg bg-slate-800 px-2 py-1">
              <Dumbbell size={12} color="#06b6d4" />
              <Text className="ml-1.5 text-xs text-slate-300">Workout</Text>
            </View>
          )}
          {sections.includeMeals && (
            <View className="flex-row items-center rounded-lg bg-slate-800 px-2 py-1">
              <Utensils size={12} color="#10b981" />
              <Text className="ml-1.5 text-xs text-slate-300">Meals</Text>
            </View>
          )}
          {sections.includeFasting && (
            <View className="flex-row items-center rounded-lg bg-slate-800 px-2 py-1">
              <Timer size={12} color="#a78bfa" />
              <Text className="ml-1.5 text-xs text-slate-300">Fasting</Text>
            </View>
          )}
          {sections.includeNutrition && (
            <View className="flex-row items-center rounded-lg bg-slate-800 px-2 py-1">
              <Grid size={12} color="#f59e0b" />
              <Text className="ml-1.5 text-xs text-slate-300">Nutrition</Text>
            </View>
          )}
          {sections.includeProgress && (
            <View className="flex-row items-center rounded-lg bg-slate-800 px-2 py-1">
              <Check size={12} color="#64748b" />
              <Text className="ml-1.5 text-xs text-slate-300">Progress</Text>
            </View>
          )}
          {sections.includeNotes && (
            <View className="flex-row items-center rounded-lg bg-slate-800 px-2 py-1">
              <AlignLeft size={12} color="#64748b" />
              <Text className="ml-1.5 text-xs text-slate-300">Notes</Text>
            </View>
          )}
        </View>
      </View>

      {/* Layout settings preview */}
      <View className="mb-4 flex-row gap-3">
        <View className="flex-1 rounded-lg bg-slate-800 p-3">
          <Text className="mb-1 text-xs text-slate-500">Layout</Text>
          <Text className="text-sm capitalize text-white">
            {template.settings.layout.orientation}
          </Text>
        </View>
        <View className="flex-1 rounded-lg bg-slate-800 p-3">
          <Text className="mb-1 text-xs text-slate-500">Font Size</Text>
          <Text className="text-sm capitalize text-white">
            {template.settings.layout.fontSize}
          </Text>
        </View>
        <View className="flex-1 rounded-lg bg-slate-800 p-3">
          <Text className="mb-1 text-xs text-slate-500">Style</Text>
          <Text className="text-sm capitalize text-white">
            {template.settings.style.headerStyle}
          </Text>
        </View>
      </View>

      {/* Footer */}
      <View className="flex-row items-center justify-between border-t border-slate-800 pt-4">
        <View>
          <Text className="text-xs text-slate-500">
            Used {template.usageCount} times
          </Text>
          <Text className="text-xs text-slate-600">
            Updated {new Date(template.updatedAt).toLocaleDateString()}
          </Text>
        </View>

        {!template.isDefault && template.status === 'active' && (
          <Pressable
            onPress={onSetDefault}
            className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-1.5"
          >
            <Text className="text-xs text-amber-400">Set as Default</Text>
          </Pressable>
        )}
      </View>
    </View>
  );
}

// Template settings panel
function TemplateSettingsPanel({
  template,
  onClose,
}: {
  template: PDFTemplate;
  onClose: () => void;
}) {
  const [settings, setSettings] = useState(template.settings);

  const updateSetting = <K extends keyof PDFTemplateSettings>(
    category: K,
    key: keyof PDFTemplateSettings[K],
    value: PDFTemplateSettings[K][keyof PDFTemplateSettings[K]]
  ) => {
    setSettings((prev) => ({
      ...prev,
      [category]: {
        ...prev[category],
        [key]: value,
      },
    }));
  };

  return (
    <View className="flex-1 border-l border-slate-700 bg-slate-900 p-5">
      {/* Header */}
      <View className="mb-6 flex-row items-center justify-between">
        <View>
          <Text className="text-lg font-semibold text-white">Template Settings</Text>
          <Text className="text-sm text-slate-400">{template.name}</Text>
        </View>
        <Pressable
          onPress={onClose}
          className="rounded-lg bg-slate-800 px-3 py-2"
        >
          <Text className="text-sm text-slate-400">Close</Text>
        </Pressable>
      </View>

      <ScrollView className="flex-1">
        {/* Layout Settings */}
        <View className="mb-6">
          <View className="mb-3 flex-row items-center">
            <Layout size={16} color="#a78bfa" />
            <Text className="ml-2 text-sm font-medium text-white">Layout</Text>
          </View>

          <View className="rounded-xl bg-slate-800 p-4">
            <View className="mb-4">
              <Text className="mb-2 text-xs text-slate-400">Orientation</Text>
              <View className="flex-row gap-2">
                {(['portrait', 'landscape'] as const).map((orientation) => (
                  <Pressable
                    key={orientation}
                    onPress={() => updateSetting('layout', 'orientation', orientation)}
                    className={cn(
                      'flex-1 rounded-lg px-4 py-2',
                      settings.layout.orientation === orientation
                        ? 'bg-violet-500'
                        : 'bg-slate-700'
                    )}
                  >
                    <Text
                      className={cn(
                        'text-center text-sm capitalize',
                        settings.layout.orientation === orientation
                          ? 'text-white'
                          : 'text-slate-400'
                      )}
                    >
                      {orientation}
                    </Text>
                  </Pressable>
                ))}
              </View>
            </View>

            <View>
              <Text className="mb-2 text-xs text-slate-400">Font Size</Text>
              <View className="flex-row gap-2">
                {(['small', 'medium', 'large'] as const).map((size) => (
                  <Pressable
                    key={size}
                    onPress={() => updateSetting('layout', 'fontSize', size)}
                    className={cn(
                      'flex-1 rounded-lg px-4 py-2',
                      settings.layout.fontSize === size ? 'bg-violet-500' : 'bg-slate-700'
                    )}
                  >
                    <Text
                      className={cn(
                        'text-center text-sm capitalize',
                        settings.layout.fontSize === size ? 'text-white' : 'text-slate-400'
                      )}
                    >
                      {size}
                    </Text>
                  </Pressable>
                ))}
              </View>
            </View>
          </View>
        </View>

        {/* Branding Settings */}
        <View className="mb-6">
          <View className="mb-3 flex-row items-center">
            <Palette size={16} color="#a78bfa" />
            <Text className="ml-2 text-sm font-medium text-white">Branding</Text>
          </View>

          <View className="rounded-xl bg-slate-800 p-4">
            <View className="mb-4 flex-row items-center justify-between">
              <Text className="text-sm text-slate-300">Show Logo</Text>
              <Switch
                value={settings.branding.showLogo}
                onValueChange={(value) => updateSetting('branding', 'showLogo', value)}
                trackColor={{ false: '#374151', true: '#a78bfa' }}
                thumbColor="#ffffff"
              />
            </View>

            <View className="mb-4 flex-row items-center justify-between">
              <Text className="text-sm text-slate-300">Show Footer</Text>
              <Switch
                value={settings.branding.showFooter}
                onValueChange={(value) => updateSetting('branding', 'showFooter', value)}
                trackColor={{ false: '#374151', true: '#a78bfa' }}
                thumbColor="#ffffff"
              />
            </View>

            <View>
              <Text className="mb-2 text-xs text-slate-400">Footer Text</Text>
              <TextInput
                value={settings.branding.footerText}
                onChangeText={(value) => updateSetting('branding', 'footerText', value)}
                className="rounded-lg bg-slate-700 px-3 py-2 text-sm text-white"
                placeholderTextColor="#64748b"
              />
            </View>
          </View>
        </View>

        {/* Section Settings */}
        <View className="mb-6">
          <View className="mb-3 flex-row items-center">
            <Grid size={16} color="#a78bfa" />
            <Text className="ml-2 text-sm font-medium text-white">Sections</Text>
          </View>

          <View className="rounded-xl bg-slate-800 p-4">
            {[
              { key: 'includeWorkout', label: 'Workout', icon: Dumbbell },
              { key: 'includeMeals', label: 'Meals', icon: Utensils },
              { key: 'includeFasting', label: 'Fasting', icon: Timer },
              { key: 'includeNutrition', label: 'Nutrition', icon: Grid },
              { key: 'includeProgress', label: 'Progress', icon: Check },
              { key: 'includeNotes', label: 'Notes', icon: AlignLeft },
            ].map(({ key, label, icon: Icon }) => (
              <View key={key} className="mb-3 flex-row items-center justify-between last:mb-0">
                <View className="flex-row items-center">
                  <Icon size={14} color="#64748b" />
                  <Text className="ml-2 text-sm text-slate-300">{label}</Text>
                </View>
                <Switch
                  value={settings.sections[key as keyof typeof settings.sections] as boolean}
                  onValueChange={(value) =>
                    updateSetting('sections', key as keyof typeof settings.sections, value)
                  }
                  trackColor={{ false: '#374151', true: '#a78bfa' }}
                  thumbColor="#ffffff"
                />
              </View>
            ))}
          </View>
        </View>

        {/* Style Settings */}
        <View className="mb-6">
          <View className="mb-3 flex-row items-center">
            <Type size={16} color="#a78bfa" />
            <Text className="ml-2 text-sm font-medium text-white">Style</Text>
          </View>

          <View className="rounded-xl bg-slate-800 p-4">
            <View className="mb-4">
              <Text className="mb-2 text-xs text-slate-400">Header Style</Text>
              <View className="flex-row gap-2">
                {(['minimal', 'standard', 'bold'] as const).map((style) => (
                  <Pressable
                    key={style}
                    onPress={() => updateSetting('style', 'headerStyle', style)}
                    className={cn(
                      'flex-1 rounded-lg px-3 py-2',
                      settings.style.headerStyle === style ? 'bg-violet-500' : 'bg-slate-700'
                    )}
                  >
                    <Text
                      className={cn(
                        'text-center text-sm capitalize',
                        settings.style.headerStyle === style ? 'text-white' : 'text-slate-400'
                      )}
                    >
                      {style}
                    </Text>
                  </Pressable>
                ))}
              </View>
            </View>

            <View className="mb-4 flex-row items-center justify-between">
              <Text className="text-sm text-slate-300">Show Icons</Text>
              <Switch
                value={settings.style.showIcons}
                onValueChange={(value) => updateSetting('style', 'showIcons', value)}
                trackColor={{ false: '#374151', true: '#a78bfa' }}
                thumbColor="#ffffff"
              />
            </View>

            <View className="flex-row items-center justify-between">
              <Text className="text-sm text-slate-300">Show Images</Text>
              <Switch
                value={settings.style.showImages}
                onValueChange={(value) => updateSetting('style', 'showImages', value)}
                trackColor={{ false: '#374151', true: '#a78bfa' }}
                thumbColor="#ffffff"
              />
            </View>
          </View>
        </View>

        {/* Save Button */}
        <Pressable className="rounded-xl bg-emerald-500 py-3">
          <Text className="text-center text-base font-semibold text-white">Save Changes</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

// Tab button
function TabButton({
  label,
  count,
  isActive,
  onPress,
}: {
  label: string;
  count?: number;
  isActive: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      onPress={onPress}
      className={cn(
        'flex-row items-center rounded-lg px-4 py-2',
        isActive ? 'bg-violet-500' : 'bg-slate-800'
      )}
    >
      <Text className={cn('text-sm font-medium', isActive ? 'text-white' : 'text-slate-400')}>
        {label}
      </Text>
      {count !== undefined && (
        <View className={cn('ml-2 rounded-full px-1.5 py-0.5', isActive ? 'bg-white/20' : 'bg-slate-700')}>
          <Text className={cn('text-xs', isActive ? 'text-white' : 'text-slate-500')}>{count}</Text>
        </View>
      )}
    </Pressable>
  );
}

// ==================== MAIN COMPONENT ====================

export default function AdminPDFTemplatesPage() {
  const [activeTab, setActiveTab] = useState<'all' | 'daily' | 'weekly'>('all');
  const [selectedTemplate, setSelectedTemplate] = useState<PDFTemplate | null>(null);
  const [templates] = useState(MOCK_TEMPLATES);

  // Filter templates
  const filteredTemplates = templates.filter((t) => {
    if (activeTab === 'all') return true;
    return t.type === activeTab;
  });

  // Count by type
  const dailyCount = templates.filter((t) => t.type === 'daily').length;
  const weeklyCount = templates.filter((t) => t.type === 'weekly').length;

  const handleEditTemplate = (template: PDFTemplate) => {
    setSelectedTemplate(template);
  };

  const handlePreviewTemplate = (template: PDFTemplate) => {
    console.log('[Admin] Previewing template:', template.id);
  };

  const handleDuplicateTemplate = (template: PDFTemplate) => {
    console.log('[Admin] Duplicating template:', template.id);
  };

  const handleDeleteTemplate = (template: PDFTemplate) => {
    console.log('[Admin] Deleting template:', template.id);
  };

  const handleSetDefault = (template: PDFTemplate) => {
    console.log('[Admin] Setting default template:', template.id);
  };

  return (
    <View className="flex-1 flex-row">
      {/* Main content */}
      <View className="flex-1 p-6">
        {/* Page header */}
        <View className="mb-6 flex-row items-center justify-between">
          <View>
            <Text className="text-2xl font-bold text-white">PDF Template Management</Text>
            <Text className="text-sm text-slate-400">
              Configure and customize PDF export templates
            </Text>
          </View>

          <Pressable className="flex-row items-center rounded-lg bg-emerald-500 px-4 py-2">
            <Plus size={16} color="white" />
            <Text className="ml-2 text-sm font-medium text-white">New Template</Text>
          </Pressable>
        </View>

        {/* Info banner */}
        <View className="mb-6 flex-row items-center rounded-xl bg-violet-500/10 border border-violet-500/20 p-4">
          <AlertCircle size={20} color="#a78bfa" />
          <View className="ml-3 flex-1">
            <Text className="text-sm font-medium text-violet-300">Template Defaults</Text>
            <Text className="text-xs text-violet-400/80">
              Default templates are used when users export PDFs without specifying a template.
              Each template type (daily/weekly) can have one default.
            </Text>
          </View>
        </View>

        {/* Tabs */}
        <View className="mb-6 flex-row gap-2">
          <TabButton
            label="All Templates"
            count={templates.length}
            isActive={activeTab === 'all'}
            onPress={() => setActiveTab('all')}
          />
          <TabButton
            label="Daily"
            count={dailyCount}
            isActive={activeTab === 'daily'}
            onPress={() => setActiveTab('daily')}
          />
          <TabButton
            label="Weekly"
            count={weeklyCount}
            isActive={activeTab === 'weekly'}
            onPress={() => setActiveTab('weekly')}
          />
        </View>

        {/* Templates grid */}
        <ScrollView className="flex-1">
          <View className="flex-row flex-wrap gap-4">
            {filteredTemplates.map((template) => (
              <View key={template.id} style={{ width: '48%' }}>
                <TemplateCard
                  template={template}
                  onEdit={() => handleEditTemplate(template)}
                  onPreview={() => handlePreviewTemplate(template)}
                  onDuplicate={() => handleDuplicateTemplate(template)}
                  onDelete={() => handleDeleteTemplate(template)}
                  onSetDefault={() => handleSetDefault(template)}
                />
              </View>
            ))}
          </View>
        </ScrollView>
      </View>

      {/* Settings panel */}
      {selectedTemplate && (
        <View style={{ width: 400 }}>
          <TemplateSettingsPanel
            template={selectedTemplate}
            onClose={() => setSelectedTemplate(null)}
          />
        </View>
      )}
    </View>
  );
}
